name: ec2-creations

on: [ push ] # trigger

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps: # stages
      - name: checkout the code
        uses: actions/checkout@v5 
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: run init
        run: terraform init 

      - name: run plan
        run: terraform plan     


